name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} installer and portable version
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'semeru'
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew jlinkZip
